### ISSUE TITLE
ManageCoursePage.js:72 Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by junaidazmat** [coryhouse/pluralsight-redux-starter#101]
# Wait, try this first...
Before opening an issue, [please try these things first](https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first).

If that list doesn't help you fix the problem, fill out the info below.

Node version: 10.9.0

npm version: 1.8.0

Operating system: Windows 10

Command line used: cmd

Steps to reproduce:
1) Go to the courses list
2) clicks on a course and there it comes. It does not show the course form.

**Comment by coryhouse** [comment]
Hi - Can you please post on the course discussion instead? Also, when you do, please share a link to your code on GitHub so I can review. Thanks!
