### ISSUE TITLE
[Help] Accessing the state of another component

### ISSUE THREAD

**Issue by email2vimalraj** [coryhouse/pluralsight-redux-starter#11]
Node version: v6.0.0

npm version: v3.8.8

Operating system: Mac OsX El Captain

Command line used: npm start -s

Steps to reproduce:
I was able to follow the tutorial and successfully run the application with no issues. Now I tried integrating login component on my own. I'm storing username and loggedIn status in the reducer state designed for login. Once logged in, I'm showing the HomePage. I would like to show the list of courses written by the logged in user on the home page. I have mock api to return the list of courses for the given username.

From the action, I'm calling a mock get api to retrieve all courses written by user. I've the below component slightly modified. But I'm unable to retrieve the list of courses in the component. The console.log step in the `componentDidMount()` is giving me `undefined`. However, I'm getting the proper results on my action which actually triggers the mock api.

**HomePage component**
```
import React, {PropTypes} from 'react';
import {connect} from 'react-redux';
import {bindActionCreators} from 'redux';
import * as courseActions from '../../actions/courseActions';
import CourseList from './CourseList';

class HomePage extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      courses: Object.assign({}, props.courses)
    };
  }

  componentDidMount() {
    this.props.actions.loadAllCoursesByUser(this.props.username)
      .then((courses) => {
        console.log(courses);
      })
      .catch(error => {
        throw(error);
      });
  }

  render() {
    return (
      <div className="container-fluid">
        <h1>Courses by me</h1>
      </div>
    );
  }
}

HomePage.propTypes = {
  username: PropTypes.string.isRequired,
  courses: PropTypes.object.isRequired,
  actions: PropTypes.object.isRequired
};

function mapStateToProps(state, ownProps) {
  return {
    username: state.user.username,
    courses: state.courses
  };
}

function mapDispatchToProps(dispatch) {
  return {
    actions: bindActionCreators(courseActions, dispatch)
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(HomePage);
```

**Action**

```
export function loadAllCoursesByUser(username) {
  return (dispatch) => {
    return CouseApi.getCoursesByUser(username).then(courses => {
      console.log(courses);
      dispatch(loadAllCoursesByUserSuccess(courses));
    }).catch(error => {
      throw(error);
    });
  };
}
```

The console.log(courses) statement in the above statement returns me the expected result.

I may be doing something wrong here. Kindly help me out.

**Comment by email2vimalraj** [comment]
I figured out the problem. I should not do this way in my component:

```
componentDidMount() {
    this.props.actions.loadAllCoursesByUser(this.props.username)
      .then((courses) => {
        console.log(courses);
      })
      .catch(error => {
        throw(error);
      });
  }
```

Instead my `componentDidMount` should be:
```
componentDidMount() {
    this.props.actions.loadAllCoursesByUser(this.props.username);
  }
```

And in my render:
```
render() {
   console.log(this.props.courses);
    return (
      <div className="container-fluid">
        <h1>Courses by me</h1>
      </div>
    );
  }
```

But I keep it open for you to confirm am I doing the proper way.

**Comment by coryhouse** [comment]
Yep, good change!
