### ISSUE TITLE
Loader cannot parse jsx

### ISSUE THREAD

**Issue by iwollmann** [coryhouse/pluralsight-redux-starter#13]
Node version: v6.2.2
npm version: v3.9.5
Operating system: windows 10

Steps to reproduce: 
1 - Clone the repository
2 - Run npm install
3 - Create a simple react component on index.js:

import React from 'react';
import { render } from 'react-dom';

class Test extends React.Component{
    render(){
        return(<div>
            Testing!!!
            </div>
        );
    }
}

render(
    <Test />,
    document.getElementById('app')
);

And get this error:
index.js Unexpected token (6:15)
You may need an appropriate loader to handle this file type.

I've revised your sample code and appearantly nothing is wrong, any clue?

**Comment by coryhouse** [comment]
I suggest installing Node 5.12. This issue occurs on some Windows machines with Node 6. Here's the full list of things to check: https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first

**Comment by iwollmann** [comment]
I found this link earlier. Change the following line in web.config.dev.js also works.
BEFORE:
`{test: /\.js$/, include: path.join(__dirname, 'src'), loaders: ['babel']}`
AFTER:
`{test: /\.js$/, exclude: /node_modules/, loaders: ['babel'] }`

But i'm receiving a lot of warnings on my terminal after start the app: "There is another module with an equal name when case is ignored."
I don't know if is a problem, but i'll ignore them for now.
Currently i'm using Node 6.3.1
Thanks Cory and congratz for the course!

**Comment by coryhouse** [comment]
Woah. So you're saying all you did was change that one line and it started working for you?

**Comment by iwollmann** [comment]
Exactly! About the warnings i mentioned, they only happen when i use the terminal inside the VSCode, when i use windows powershell everything is ok.

**Comment by wcphart** [comment]
Late to the party but wanted to add to the detail for others running into this. Followed the tutorial from PS that referenced the starter pack, and using VS Codes built in command line, it fails. Using Windows command line, no errors.

Making the line change mentioned above in VS Code gets past error, but fills log with warning of another module with an equal name when case is ignored.

For me, in Windows 10 neither line above causes any errors or warnings in Windows command line. Guess its time to consider a different IDE again.

@coryhouse Loving those tutorials on PluralSight. Thanks!

**Comment by iwollmann** [comment]
@wcphart Many issues i've been having was resolved when i started to use npm in version 3 instead of version 1.
