### ISSUE TITLE
Bug in saveAuthor method of mockAuthorApi.js causes author.id to always be present, even during create actions

### ISSUE THREAD

**Issue by compumike08** [coryhouse/pluralsight-redux-starter#14]
Node version: 4.4.7

npm version: 2.15.8

Operating system: Windows 7 (64-bit)

Command line used: Git BASH for Windows

Steps to reproduce: When you add the ability to add authors to the react/redux code, your `saveAuthor` method in this repository's `mockAuthorApi.js` file doesn't make a local copy of the author object passed into it before manipulating it. This causes `saveAuthor` to manipulate the author object in the "client-side" code directly. If you try to create a new author, when the `saveAuthor` method in `mockAuthorApi.js` is invoked it will generate and add an id to the author object. But since it is manipulating the author object directly, the id gets added to the "client-side" author object and causes the "client-side" code to always think you are doing an update instead of a create action.

**Comment by coryhouse** [comment]
Resolved with this PR: https://github.com/coryhouse/pluralsight-redux-starter/pull/16
