### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by tsvetkovpro** [coryhouse/pluralsight-redux-starter#17]
Node version: 6.2.0

npm version: 3.8.9

Operating system: Microsoft Windows 8.1 Professional v6.3.10586.494 x64

Command line used: cmd, bash 

Steps to reproduce: when i add this code : 

```javascript
  const authorsFormattedForDropdown = state.authors.map(author => {
    return {
      value: author.id,
      text: author.firstName + ' ' + author.lastName
    };
  });
```

in file src\components\course\ManageCoursePage.js i have some error: 

> Uncaught TypeError: Cannot read property 'map' of undefined

i repeat by you. but you don't have this error on course. help me please?

**Comment by coryhouse** [comment]
That error means state.authors isn't getting populated. I'd set a breakpoint in your mapStateToProps function and trace back further from there if necessary.

**Comment by tsvetkovpro** [comment]
oh , thx a lot

**Comment by shoesandsocks** [comment]
in case anyone else ends up here (it's currently the top hit for "pluralsight error cannot read property"!), I hit the same error while hand-coding along with Cory's videos. The solution was remembering to add "authors" to the combineReducers (at /src/reducers/index.js).

`const rootReducer = combineReducers({
  courses,
  authors
});`

**Comment by coryhouse** [comment]
in case anyone else ends up here (it's currently the top hit for "pluralsight error cannot read property"!), the solution is remembering to add "authors" to the combineReducers (at /src/reducers/index.js).

const rootReducer = combineReducers({
courses,
authors
});

**Comment by ashfaqrafi** [comment]
@coryhouse the above solution worked for me in the ManageCoursePage.js mapStateToProps function but after that while I am running the project I get another similar error:
SelectInput.js:15 Uncaught TypeError: Cannot read property 'map' of undefined
here is the code of SelectInput.js file:
`import React, {PropTypes} from 'react';

const SelectInput = ({name, label, onChange, defaultOption, value, error, options}) => {
  return (
    <div className="form-group">
      <label htmlFor={name}>{label}</label>
      <div className="field">
        {/* Note, value is set here rather than on the option - docs: https://facebook.github.io/react/docs/forms.html */}
        <select
          name={name}
          value={value}
          onChange={onChange}
          className="form-control">
          <option value="">{defaultOption}</option>
          {options.map((option) => {
            return <option key={option.value} value={option.value}>{option.text}</option>;
          })
          }
        </select>
        {error && <div className="alert alert-danger">{error}</div>}
      </div>
    </div>
  );
};

SelectInput.propTypes = {
  name: PropTypes.string.isRequired,
  label: PropTypes.string.isRequired,
  onChange: PropTypes.func.isRequired,
  defaultOption: PropTypes.string,
  value: PropTypes.string,
  error: PropTypes.string,
  options: PropTypes.arrayOf(PropTypes.object)
};

export default SelectInput;
`
