### ISSUE TITLE
Warning: Failed Context Types: Required context `router` was not specified in `ManageCoursePage`.

### ISSUE THREAD

**Issue by tsvetkovpro** [coryhouse/pluralsight-redux-starter#18]
Node version: 6.2.0

npm version: 3.8.9

Operating system: Microsoft Windows 8.1 Professional v6.3.10586.494 x64

Command line used: cmd, bash

Steps to reproduce: when i add this code :

**When i create ManageCoursePage.test.js with this code:** 

```javascript
import React from 'react';
import expect from 'expect';
import {mount, shallow} from 'enzyme';
import {ManageCoursePage} from './ManageCoursePage';

describe('Manage Course Page', () => {
  it('sets error message when trying to save empty title', () => {
    const props = {
      authors: [],
      actions: { saveCourse: () => { return Promise.resolve(); }},
      course: {id: '', watchHref: '', title: '', authorId: '', length: '', category: ''}
    };

    const wrapper = mount(<ManageCoursePage {...props}/>);
    const saveButton = wrapper.find('input').last();
    expect(saveButton.prop('type')).toBe('submit');
    saveButton.simulate('click');
    expect(wrapper.state().errors.title).toBe('Title must be at least 5 characters.');
  });
});
```
I run:

> npm run test -- --watch

and i got this error:

> Warning: Failed Context Types: Required context `router` was not specified in `ManageCoursePage`.

And you code work fine, but my same dosen't work well

**Comment by tsvetkovpro** [comment]
> import React, {PropTypes} from 'react';
> import {connect} from 'react-redux';
> import {bindActionCreators} from 'redux';
> import * as courseActions from '../../actions/courseActions';
> import CourseForm from './CourseForm';
> import toastr from 'toastr';
> 
> 
> 
> export class ManageCoursePage extends React.Component {
>   constructor(props, context) {
>     super(props, context);
> 
>     this.state = {
>       course: Object.assign({}, props.course),
>       errors: {},
>       saving: false
>     };
> 
>     this.updateCourseState = this.updateCourseState.bind(this);
>     this.saveCourse = this.saveCourse.bind(this);
>   }
> 
>   componentWillReceiveProps(nextProps) {
>     if (this.props.course.id != nextProps.course.id) {
>       // necessary to populate form when existing course is loaded directly
>       this.setState({course: Object.assign({}, nextProps.course)});
>     }
>   }
> 
>   updateCourseState(event) {
>     const field = event.target.name;
>     let course = this.state.course;
>     course[field] = event.target.value;
>     return this.setState({course: course});
>   }
> 
>   courseFormIsValid() {
>     let formIsValid = true;
>     let errors = {};
> 
>     if (this.state.course.title.length < 5) {
>       errors.title = 'Title must be at least 5 characters.';
>       formIsValid = false;
>     }
> 
>     this.setState({errors: errors});
>     return formIsValid;
>   }
> 
>   saveCourse(event) {
>     event.preventDefault();
> 
>     if(!this.courseFormIsValid()) {
>       return;
>     }
> 
>     this.setState({saving: true});
>     this.props.actions.saveCourse(this.state.course)
>       .then(() => this.redirect())
>       .catch(error => {
>         toastr.error(error);
>         this.setState({saving: false});
>       });
>   }
> 
>   redirect() {
>     this.setState({saving: false});
>     toastr.success('Курс сохранён');
>     this.context.router.push('/courses'); // as promise result on 38 then
>   }
> 
>   render() {
>     return (
>       <CourseForm
>         allAuthors={this.props.authors}
>         onChange={this.updateCourseState}
>         onSave={this.saveCourse}
>         course={this.state.course}
>         errors={this.state.errors}
>         saving={this.state.saving}
>       />
>     );
>   }
> }
> 
> ManageCoursePage.propTypes = {
>   course: PropTypes.object.isRequired,
>   authors: PropTypes.array.isRequired,
>   actions: PropTypes.object.isRequired
> };
> 
> // pull in the React Router context so router is available on this.context.router
> ManageCoursePage.contextTypes = {
>   router: PropTypes.object.isRequired
> };
> 
> function getCourseById(courses, id) {
>   const course = courses.filter(course => course.id == id);
>   if (course) return course[0];
>   return null;
> }
> 
> function mapStateToProps(state, ownProps) {
>   const courseId = ownProps.params.id; //from the path `/course/:id`
> 
>   let course = {id: '', watchHref: '', title: '', authorId: '', length: '', category: ''};
>   if (courseId && state.courses.length > 0) {
>     course = getCourseById(state.courses, courseId);
>   }
> 
>   const authorsFormattedForDropdown = state.authors.map(author => {
>     return {
>       value: author.id,
>       text: author.firstName + ' ' + author.lastName
>     };
>   });
> 
>   return {
>     course: course,
>     authors: authorsFormattedForDropdown
>   };
> }
> 
> function mapDispatchToProps(dispatch) {
>   return {
>     actions: bindActionCreators(courseActions, dispatch)
>   };
> }
> 
> export default connect(mapStateToProps, mapDispatchToProps)(ManageCoursePage);
>

**Comment by coryhouse** [comment]
Since my code works fine and yours doesn't, have you diff'd the two? I don't see anything obviously wrong at a glance, but It's likely a simple typo.

**Comment by tmxyz** [comment]
@tsvetkovpro remove `isRequired`. You are getting this warning because you have:
```jsx
ManageCoursePage.contextTypes = {
  router: PropTypes.object.isRequired,
};
```
instead of 
```jsx
ManageCoursePage.contextTypes = {
  router: PropTypes.object,
};
```

**Comment by coryhouse** [comment]
Good catch @tmxyz. Thanks for the response! 👍
