### ISSUE TITLE
Can't successfully build production version

### ISSUE THREAD

**Issue by wowkin2** [coryhouse/pluralsight-redux-starter#19]
Course name:
#### Building Applications with React and Redux in ES6
Node version:
`v6.3.1`
npm version:
`v3.10.3`
Operating system:
`Linux 3.13.0-93-generic`
Command line used:
`"/usr/bin/nodejs" "/usr/bin/npm" "run" "build"`
Steps to reproduce:
* write code by example from video or copy files provided with course
* see following errors in WebStorm terminal:
```/home/username/WebstormProjects/sample_reactjs/webpack.config.dev-compiled.js.map (1/0)
✖  1:11  Parsing error: Unexpected token :
/home/username/WebstormProjects/sample_reactjs/webpack.config.prod-compiled.js.map (1/0)
✖  1:11  Parsing error: Unexpected token :```
* see build traceback with errors:
```
Your app has been compiled in production mode and written to /dist. It's ready to roll!

> react-redux-sample@1.0.0 postbuild /home/username/WebstormProjects/sample_reactjs
> babel-node tools/distServer.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at EventEmitter.listen (/home/username/WebstormProjects/sample_reactjs/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (distServer.js:18:5)
    at Module._compile (module.js:541:32)
    at loader (/home/username/WebstormProjects/sample_reactjs/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/username/WebstormProjects/sample_reactjs/node_modules/babel-register/lib/node.js:168:7)

npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-redux-sample@1.0.0 postbuild: `babel-node tools/distServer.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-sample@1.0.0 postbuild script 'babel-node tools/distServer.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/distServer.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-sample
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-sample
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/username/WebstormProjects/sample_reactjs/npm-debug.log

```

**Comment by coryhouse** [comment]
You already have something running on port 3000. Either select a different port or kill the process that's already running (perhaps another instance of this kit)

**Comment by wowkin2** [comment]
thanks, it helped.
I forgot to stop dev.version :-)
