### ISSUE TITLE
error on npm start. "Module parse failed. You may need an appropriate loader to handle this file type."

### ISSUE THREAD

**Issue by Assam** [coryhouse/pluralsight-redux-starter#2]
I get following error while doing npm start. It seems(only assuming) that webpack is unable to load babel loader. 
![image](https://cloud.githubusercontent.com/assets/4727391/15508878/486fca5a-21e2-11e6-9d6a-7c037e35551e.png)

**Comment by coryhouse** [comment]
Is the babel loader configured in webpack.config.js?

**Comment by Assam** [comment]
Yes i am using same file as uploaded on Github.

**Comment by coryhouse** [comment]
Can you post your solution so I can try running it?

Also, what version of node and npm are you using?

And what OS and command line?

**Comment by Assam** [comment]
Node: 6.2.0
Npm: 3.9.2
OS: Windows 7
Btw i did download zip from Pluralsight and it also gives same error. If i comment out following function then it works fine but i guess that's where main logic is.
render(
  (<Router history={browserHistory} routes={routes} />),
  document.getElementById('app')
);

**Comment by coryhouse** [comment]
Note that your error is on line 9 of index.js. It appears you just have a syntax error on line 9 of index.js

**Comment by Assam** [comment]
I was also under same impression until i tried solution uploaded on pluralsight. Even that solution also points error at same line of code.

**Comment by coryhouse** [comment]
Line 9 doesn't exist in index.js in this starter kit. What error do you receive when you simply clone this starter kit without any changes?

**Comment by Assam** [comment]
Well in starter kit index.js only has console statement so it works fine. Only issue is when i try to add react specific code then it breaks. 
Anyhow if i replace following line in webpack.config.dev.js then i am able to execute the project(with gazillion warnings in command prompt)
`{ test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" }`
Can this be specific to environment?

**Comment by coryhouse** [comment]
I'm confused. That line doesn't exist in the starter kit's webpack.config. It should read:

`{test: /\.js$/, include: path.join(__dirname, 'src'), loaders: ['babel']},`

**Comment by coryhouse** [comment]
Also, I just realized that npm-shrinkwrap.json should be deleted from the exercise files solution if you're on Windows (I created it on Mac so it causes an issue on Windows). After you delete npm-shrinkwrap.json, re-run npm install.

**Comment by Assam** [comment]
I am sorry i should have precisely mention on what i replaced
So i replaced following line:
`{test: /\.js$/, include: path.join(__dirname, 'src'), loaders: ['babel']}`
WITH
`{ test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" }`
and then it worked but as I said I see gazillion warning messages.

**Comment by coryhouse** [comment]
Why did you change that line? What error do you receive with the line set to what's in the starter kit?

**Comment by Assam** [comment]
Well i get the error as i have highlighted in the subject of this issue
### error on npm start. "Module parse failed. You may need an appropriate loader to handle this file type."

**Comment by coryhouse** [comment]
Gotcha. Please post your full solution, including node_modules, and I'll try running it on my Windows machine to see if I can reproduce.

**Comment by Assam** [comment]
[http://www.filedropper.com/tvapp](url)

**Comment by coryhouse** [comment]
Hrmm...I'm able to run your app just fine with Node 6.2.0/npm 3.8.6 on Windows 7.

But in a VM running Windows 8.1, I can reproduce your issue using Node 6.2.0/npm 3.8.6. I downgraded to the latest [5.x version](https://nodejs.org/dist/latest-v5.x/) of Node (5.11.1), and it worked fine.

So my suggestion for now is to install the latest [5.x version](https://nodejs.org/dist/latest-v5.x/) of Node. 6.x is bleeding edge and I suspect it's causing issues with some configurations.

Please let me know if 5.11.1 works fine for you.

**Comment by coryhouse** [comment]
@Assam Did using 5.11.1 solve your issue? That worked for me and another person.

**Comment by coryhouse** [comment]
Closing since no response. Others in course discussion mentioned moving to 5.11 fixed it for them.

**Comment by Assam** [comment]
Cory, I am sorry I couldn't revert back to you on this. I was busy in some other projects. Anyhow i think its fair to close the bug.

**Comment by alf** [comment]
This relates to https://github.com/webpack/webpack/issues/2462 and https://github.com/babel/babel-loader/issues/198 for anyone ending up here in the future.

**Comment by coryhouse** [comment]
@Assam Just FYI - Installing the latest version of Node (6.2.1) resolved this for me.

I'm still unclear if Webpack, acorn, or Node is the root cause, but it works on Windows now in 6 for me.

**Comment by jazznov** [comment]
I'm having this exact same issue with both 6.2.0 and 6.2.1 on Win 7. Switching to 4.4.5 (current LTS version) seems to fix it.

**Comment by OnlyRefat** [comment]
having no clue what is the problem. anyone faced and fixed the probem???

http://stackoverflow.com/questions/38669804/you-may-need-an-appropriate-loader-to-load-this-file-on-windows-with-webpack-not

**Comment by coryhouse** [comment]
@OnlyRefat Try changing this line: https://github.com/coryhouse/pluralsight-redux-starter/blob/master/webpack.config.dev.js#L28

to this:

{test: /\.js$/, exclude: /node_modules/, loaders: ['babel'] }

This issue is also being discussed in https://github.com/coryhouse/pluralsight-redux-starter/issues/13, and someone reported this change worked for them.

If the change above doesn't fix it, be sure to check this list: https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first
