### ISSUE TITLE
Deployment options

### ISSUE THREAD

**Issue by wowkin2** [coryhouse/pluralsight-redux-starter#20]
How to deploy this project on some hosting (e.g. on Heroku)?

**Comment by coryhouse** [comment]
Since the build simply creates static files, you just need to upload the static files to the web root on your host. You could Automate it via an npm script or by calling a separate Node script if complicated.

**Comment by wowkin2** [comment]
What about some server configuration?
Because on Heroku we can call some executive script that should listen to some port and return HTTP responses with files (html, js, etc.)

**Comment by coryhouse** [comment]
You're just hosting static files, so the process is whatever process your host requires to serve static. I can't speak directly to Heroku, but suggest posting on Stackoverflow.
