### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by samundrak** [coryhouse/pluralsight-redux-starter#25]
Node version: v6

npm version: v3.10.3

Operating system: Ubuntu 16 LTS

Command line used: -

Steps to reproduce: -

Just followed the tutorial after creating routes, components and while seeing on page i got this
error.

I got the error here 
![image](https://cloud.githubusercontent.com/assets/3079452/18639327/2fc7aa30-7eb3-11e6-9cef-ed5b5d8c846c.png)

**Comment by dsinkey** [comment]
What did you do to fix this? I'm getting the same thing.

**Comment by coryhouse** [comment]
You likely have a typo in your constructor. If you share the error and the file, I can help.

**Comment by matthetherington** [comment]
The c in component should be uppercase.

```
class App extends React.Component {
```
