### ISSUE TITLE
Windows hot reloading not working

### ISSUE THREAD

**Issue by arhtudormorar** [coryhouse/pluralsight-redux-starter#27]
Node version: v6.6.0

npm version: 3.10.8

Operating system: Windows 7

Command line used: Ctrl+S on a js file

Steps to reproduce: Download repository on Windows 7. npm install. npm start -s. Modify index.js + save

Error: 
`[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
process-update.js?e13e:89 
[HMR]  - ./src/index.js
process-update.js?e13e:128 
[HMR] Reloading page`

**Comment by coryhouse** [comment]
I've cloned this project and run it on Windows 7. The index.js page fully reloads when I change the console.log statement.

**Comment by arhtudormorar** [comment]
Hi Cory and thanks for the quick response! 
Yes it fully reloads but modules are not replaced without fully reloading. I have tried a solution using webpack dev server and it works but I cannot configure it on express..

**Comment by coryhouse** [comment]
Ah, then Webpack is operating the same for you as me. As they say in their docs, it's not perfect. Because this is the root file, I believe that's why it can't be hot reloaded.

**Comment by arhtudormorar** [comment]
Even if you add other modules they do not hot update. When the application becomes larger, and there is more compiling to do (like decorators and flow types - which by the way took me about 3 weeks to get them working on Windows) + an eventual fly-in animation of the view, from save to page reload might take about 7 seconds. If you do not find a solution to this I will keep searching and let you know if I find the answer first.
