### ISSUE TITLE
Mocha test issue.

### ISSUE THREAD

**Issue by pkoppel** [coryhouse/pluralsight-redux-starter#29]
Node version: v0.12.2

npm version: 2.7.4

Operating system: Windows 8.1 Enterprise

Command line used: windows default cmd

Steps to reproduce: I was following your Pluralsight Video and when it was time to test the mocha tests I got the following error message:

![9-30-2016 12-08-25 pm](https://cloud.githubusercontent.com/assets/6863767/19000194/e469d17e-8706-11e6-877c-0caffc13c833.png)

**Comment by coryhouse** [comment]
You're running an older version of Node than I tested or suggested. I recommend running at least version 4. 

Please also check this list: https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first

Please post back if issue persists.
