### ISSUE TITLE
syntax error found while attempting to run first version of "start" script

### ISSUE THREAD

**Issue by rodnolan** [coryhouse/pluralsight-redux-starter#32]
Node version: 6.9.1, 7.1.0, 5.12.0 (I've tried three times, with the same result each time) 
npm version: 3.10.9
Operating system: Windows 7 Enterprise SP1
Command line used: npm start
IDE: IntelliJ IDEA 2016.2.4
Steps to reproduce: I've been following along with the video (Environment Setup/Create Start Script) and copy/pasting the code from the github repo. 

I get this error when attempting to run "npm start"

![image](https://cloud.githubusercontent.com/assets/1766935/20192179/c726ec08-a756-11e6-8651-5ce3927a007c.png)

I reviewed issue #30 but my problem is different. 

Here is my npm-debug.log

[npm-debug.log.txt](https://github.com/coryhouse/pluralsight-redux-starter/files/584341/npm-debug.log.txt)

I ran npm install and there were no signs of any problems. This is the first snag I've run into.

Suggestions?

**Comment by coryhouse** [comment]
Can you confirm you have a .babelrc file in the root of the project?

**Comment by rodnolan** [comment]
Thanks for the suggestion @coryhouse. I placed some of the files that should have been in the root folder inside the /src folder. After carefully moving those files into the correct location, I'm back on track. Thanks for the quick response.

**Comment by coryhouse** [comment]
Good deal! :)
