### ISSUE TITLE
chore: upgrade to webpack 2

### ISSUE THREAD

**Issue by cdoremus** [coryhouse/pluralsight-redux-starter#34]
This issue is a request to upgrade the code (webpack.config.dev.js) to webpack 2.

**Comment by vjwilson** [comment]
@cdoremus @coryhouse ,

As of today (11/14/2016), Webpack 2 is listed **on the Webpack site** as "currently work in progress" (https://webpack.github.io/docs/roadmap.html)

There is a beta available to try, but I think upgrading the course to something still in beta would be unwise.

If anyone wants to adapt their code as they go through the course to Webpack 2, have at it. Please don't make everybody else beta testers as they are trying to learn.

**Comment by coryhouse** [comment]
Totally agree @vjwilson. I'm really excited about Webpack 2, but the course will stay as is for now. The great news is upgrading to Webpack 2 is easy. I plan to publish a simple upgrade path when Webpack 2 final goes live.

**Comment by J4ck4l0pe** [comment]
Webpak 2 is now the default version. Can we upgrade? I tried, without success so far.

**Comment by spencersmb** [comment]
Also having trouble with adding custom aliases via resolve in webpack....any ideas?

Thanks!

```
...
resolve: {
    root: __dirname,
    modulesDirectories: [
      'node_modules',
      './src/components',
      './src/api'
    ],
    alias: {
      app: 'src/components/app.js'
    },
    extensions: ['', '.js']
  }
...
```

I get this error -> 
  ✖  3:17  Unable to resolve path to module 'app'  import/no-unresolved

**Comment by coryhouse** [comment]
Upgrading to webpack 2 is easy. Check out the minor differences in the final course demo's webpack configs in this: https://github.com/coryhouse/pluralsight-redux-app-used-to-build-script/pull/1
