### ISSUE TITLE
Missing files from course

### ISSUE THREAD

**Issue by bbarwick-fdg** [coryhouse/pluralsight-redux-starter#35]
Many of the files included in the `react-redux-react-router-es6.zip` downloaded from the **Excercise files** page of the course are missing from this repo.  Not sure if this was intentional but I found it confusing after cloning the repo from Github and then finding that the files are missing when I got to the **Initial App Structure** chapter.

**Comment by coryhouse** [comment]
That's intentional. This repo is merely the starter, hence the name. :)

Pluralsight asks that I not share completed course demos since they're a subscriber benefit.

**Comment by bbarwick-fdg** [comment]
Thx for explanation. :-)
