### ISSUE TITLE
Include faker.js in the MockAPI will allow to generate big amount of data easily

### ISSUE THREAD

**Issue by jquintozamora** [coryhouse/pluralsight-redux-starter#36]
Type: Enhancement.

I could do a pull request if you want...

Regards!

**Comment by coryhouse** [comment]
Hi @jquintozamora - This starter is specifically for my Redux course, and I don't currently discuss faker in the course, so I need to leave this as is. 

That said, I may add a mock API set up to React Slingshot (my full-featured starter kit) soon.

But thanks for the suggestion!

**Comment by jquintozamora** [comment]
Cool @coryhouse , looking forward to see React Slingshot! . Cheers
