### ISSUE TITLE
Not having to bind every event method

### ISSUE THREAD

**Issue by Todilo** [coryhouse/pluralsight-redux-starter#38]
I want to use arrow function. I have tried adding stage-0 to babel but not working fully as intended.

**Comment by coryhouse** [comment]
Sorry, I need to keep this repository as is to assure it matches the course. If you want to see an example project that supports using class properties (they're not called arrow functions when being used to replace a method in a class), then check out React Slingshot: https://github.com/coryhouse/react-slingshot
