### ISSUE TITLE
API delete course not using correct property

### ISSUE THREAD

**Issue by stuartdga** [coryhouse/pluralsight-redux-starter#39]
Node version:

npm version:

Operating system:

Command line used:

Steps to reproduce: The current code uses const indexOfCourseToDelete = courses.findIndex(course => {
          course.courseId == courseId;
        });
But I think the actual property should just be "id" and not "courseId"

**Comment by coryhouse** [comment]
Good catch! 👍  Fixed: https://github.com/coryhouse/pluralsight-redux-starter/commit/47751502f4a30d6c581d3e2c51bca5e6138ba031
