### ISSUE TITLE
some little omissions in the PluralSight course

### ISSUE THREAD

**Issue by ATGardner** [coryhouse/pluralsight-redux-starter#4]
1. Add authorReducer to the rootReducer
2. Add "import {browserHistory} from 'react-router';" to CoursesPage
3. Add "this.saveCourse = this.saveCourse.bind(this);" to ManageCoursePage ctr

And I think the next one is an actual implementation bug:
4. courseActions#saveCourse checks id on course returned from API. Will always have id -> will always call "updateCourseSuccess". Should check on input course reference instead

I hope to finish the course this weekend, and I'll update here if I find anything else.

**Comment by coryhouse** [comment]
Thanks for reporting!

1. Will already be fixed in an upcoming patch.
2. Good catch! I'll patch this.
3. I add this already in m10-12 at :27.
4. Will already be fixed in an upcoming patch.

**Comment by coryhouse** [comment]
Just FYI for anyone reading. These issues are now fixed in the published course.
