### ISSUE TITLE
_reactDom.render not a function? (Initial App Structure > Create Head)

### ISSUE THREAD

**Issue by injune1123** [coryhouse/pluralsight-redux-starter#40]
Node version:6.9.2

npm version:4.0.3

Operating system: Mac OS X Yosemite

Command line used:npm install, npm start

Steps to reproduce: npm start

I was following the video and got stuck in the  Initial App Structure > Create Head session. I got an error in the console
  !  8:17  'children' is missing in props validation  react/prop-types

Then I open my chome dev tool, I saw an error message "(0 , _reactDom.render) is not a function(…)". 

This is my code, does anyone have any idea why the error is happening and how should I fix it?

<pre>
import 'babel-polyfill';
import React from 'react';
import { render } from 'react-dom';
import { Router, browserHistory } from 'react-router';
import routes from './routes';
import './styles/styles.css'; //Webpack can import CSS files too!
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';

render(
   "<" Router history={browserHistory} routes={routes} /  ">"
  document.getElementById('app')
);

</pre>

**Comment by coryhouse** [comment]
Your render call doesn't have any JSX inside, so there's nothing to render.

**Comment by injune1123** [comment]
Thanks for getting back to me! 
Oh, the JSX was not showing up. I think github thinks anything inside <> is HTML and did not show them. I edited my question it by adding quotation marks around them.  The question marks do not exist in my actual code. 

Here is my package.json
{
  "name": "pluralsight-redux-starter",
  "version": "1.0.0",
  "description": "Starter kit for React and Redux Pluralsight course by Cory House",
  "scripts": {
    "prestart": "babel-node tools/startMessage.js",
    "start": "npm-run-all --parallel open:src lint:watch test:watch",
    "open:src": "babel-node tools/srcServer.js",
    "lint": "node_modules/.bin/esw webpack.config.* src tools",
    "lint:watch": "npm run lint -- --watch",
    "test": "mocha --reporter progress tools/testSetup.js \"src/**/*.test.js\"",
    "test:watch": "npm run test -- --watch"
  },
  "author": "Cory House",
  "license": "MIT",
  "dependencies": {
    "babel-polyfill": "6.8.0",
    "bootstrap": "3.3.6",
    "jquery": "2.2.3",
    "material-ui": "^0.16.4",
    "react": "^15.4.1",
    "react-dom": "15.0.2",
    "react-redux": "4.4.5",
    "react-router": "2.4.0",
    "react-router-redux": "4.0.4",
    "react-tap-event-plugin": "^1.0.0",
    "redux": "3.5.2",
    "redux-thunk": "2.0.1",
    "toastr": "2.1.2"
  },
  "devDependencies": {
    "babel-cli": "6.8.0",
    "babel-core": "6.8.0",
    "babel-loader": "6.2.4",
    "babel-plugin-react-display-name": "2.0.0",
    "babel-preset-es2015": "6.6.0",
    "babel-preset-react": "6.5.0",
    "babel-preset-react-hmre": "1.1.1",
    "babel-register": "6.8.0",
    "colors": "1.1.2",
    "compression": "1.6.1",
    "cross-env": "1.0.7",
    "css-loader": "0.23.1",
    "enzyme": "2.2.0",
    "eslint": "2.9.0",
    "eslint-plugin-import": "1.6.1",
    "eslint-plugin-react": "5.0.1",
    "eslint-watch": "2.1.11",
    "eventsource-polyfill": "0.9.6",
    "expect": "1.19.0",
    "express": "4.13.4",
    "extract-text-webpack-plugin": "1.0.1",
    "file-loader": "0.8.5",
    "jsdom": "8.5.0",
    "mocha": "2.4.5",
    "nock": "8.0.0",
    "npm-run-all": "1.8.0",
    "open": "0.0.5",
    "react-addons-test-utils": "15.0.2",
    "redux-immutable-state-invariant": "1.2.3",
    "redux-mock-store": "1.0.2",
    "rimraf": "2.5.2",
    "style-loader": "0.13.1",
    "url-loader": "0.5.7",
    "webpack": "1.13.0",
    "webpack-dev-middleware": "1.6.1",
    "webpack-hot-middleware": "2.10.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/coryhouse/pluralsight-redux-starter"
  }
}

index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Movie</title>
</head>
<body>
	<header>
		<a></a>			
		<nav>	
			<li>recommended</li>
		</nav>
		<nav class="account">
			<li>search</li>
			<li>account</li>
		</nav>
	</header>
	<div id="app"></div>
	<script src="/bundle.js"></script>
</body>
</html>

index.js
import 'babel-polyfill';
import React from 'react';
import { render } from 'react-dom';
import { Router, browserHistory } from 'react-router';
import routes from './routes';
import './styles/styles.css'; //Webpack can import CSS files too!
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';


render(
    <Router history={browserHistory} routes={routes} />,
  document.getElementById('app')
);


routes.js
import React from 'react';
import { Route, IndexRoute } from 'react-router';
import App from './components/App';
import HomePage from './components/home/HomePage';
import AboutPage from './components/about/AboutPage';

export default(
	<Route path="/" component={App}>
		<IndexRoute component={HomePage} />
		<Route path="about" component={AboutPage} />
	</Route>
);

App.js

import React, {PropTypes} from 'react';

class App extends React.Component {
	render(){
		return(
			<div className="container-fluid">
				<p>Header here...</p>
				{this.props.children}
			</div>
		);
	}
}

App.PropTypes = {
	children: PropTypes.object.isRequired
};

export default App;

Here is the error I got in browser
![error in browser](https://cloud.githubusercontent.com/assets/12467641/21054309/19bdff28-bdfb-11e6-9ee1-e026e0e80629.png)

Here is the error I got in my terminal
![error in console](https://cloud.githubusercontent.com/assets/12467641/21054323/37be3880-bdfb-11e6-8637-56d622a07ea1.png)

**Comment by coryhouse** [comment]
Can you please post your full solution to GitHub so I can run it? I can't easily help with the pasted code above.

**Comment by injune1123** [comment]
Sure. Sounds like a good idea. https://github.com/injune1123/IMovie/tree/react
After cloning the project, you will need the following commands to reproduce the error
$npm install 
$npm start

Thanks again for your help!

**Comment by coryhouse** [comment]
You need to use the same version of react-dom as react. I changed the react-dom version in package.json to 15.4.1 and it worked. :)
