### ISSUE TITLE
Typescript version

### ISSUE THREAD

**Issue by Rajivhost** [coryhouse/pluralsight-redux-starter#41]
Hi, it Will be great if we can have this project config + Typescrip working.

**Comment by coryhouse** [comment]
Sorry, this repo is for the Pluralsight course so it's focused solely on getting someone started with Babel. That said, there are some interesting options here: http://andrewhfarmer.com/starter-project/

**Comment by Rajivhost** [comment]
Ok, thanks you for the link.
