### ISSUE TITLE
How to make eslint work with modulesDirectories?

### ISSUE THREAD

**Issue by cihadturhan** [coryhouse/pluralsight-redux-starter#45]
Node version: v6.9.1

npm version: v3.10.8

Operating system: mac os sierra

Command line used: npm start

Steps to reproduce:

Hey Cory, 

I'm trying to work eslint work with WebPack modulesDirectories option as described [here](https://gist.github.com/ryanflorence/daafb1e3cb8ad740b346#gistcomment-1376396). However, eslint throws the following error and prevents webpack build

```
/Users/cihadturhan/Desktop/github/dashboard-react/src/client/App/components/NavbarApp.js (1/0)
  ✖  2:22  Unable to resolve path to module 'components/AppImage.js'  import/no-unresolved
```

Can you guide me how to make eslint work? Thanks in advance.

**Comment by coryhouse** [comment]
Perhaps you just need to tweak your path to ./components/AppImage.js?

**Comment by cihadturhan** [comment]
Thanks. I solved the issue. It requires eslint-loader and webpack config in ES5
