### ISSUE TITLE
I use Intellij - Can I able to Install React Template - Please provide me the steps

### ISSUE THREAD

**Issue by svemula09** [coryhouse/pluralsight-redux-starter#47]

**Comment by coryhouse** [comment]
Sorry, I don't have the steps for Intellij

**Comment by svemula09** [comment]
Please provide me for webstorm. I will use webstorm

**Comment by coryhouse** [comment]
Sorry, I don't have the source handy, but someone wrote down the details here: http://www.davidboyne.co.uk/2016/05/24/react-templates-in-webstorm.html
