### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by DylanVerstraete** [coryhouse/pluralsight-redux-starter#49]
After npm install I tried to run but I got this error message.

![image](https://cloud.githubusercontent.com/assets/17138347/22853429/6b5f5aa6-f056-11e6-8f8e-e6e426c4cb5f.png)

**Comment by coryhouse** [comment]
That means Mocha can't find any tests. Create at least test and place it in a file ending in test.js, within your src dir.
