### ISSUE TITLE
Exit status 127 - This is most likely a problem with the pluralsight-redux-starter package not with npm itself.

### ISSUE THREAD

**Issue by jason31795** [coryhouse/pluralsight-redux-starter#5]
sudo npm start

> pluralsight-redux-starter@1.0.0 prestart /home/jason/Documents/reacttest/pluralsight-redux-starter-master
> babel-node tools/startMessage.js

/usr/bin/env: node: No such file or directory

npm ERR! pluralsight-redux-starter@1.0.0 prestart: `babel-node tools/startMessage.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the pluralsight-redux-starter@1.0.0 prestart script.
npm ERR! This is most likely a problem with the pluralsight-redux-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/startMessage.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pluralsight-redux-starter
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-16-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/jason/Documents/reacttest/pluralsight-redux-starter-master
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jason/Documents/reacttest/pluralsight-redux-starter-master/npm-debug.log
npm ERR! not ok code 0

**Comment by coryhouse** [comment]
You're running an old version of Node that isn't supported by this starter kit. Please upgrade to Node 6, delete node modules, then re-run npm install.

**Comment by folivi** [comment]
Having the same issue despite node 6 and npm 3.9.5

➜  learnRedux npm run lint                      

> learning-redux@1.0.0 lint /Users/folivi/Documents/projects/nodejs/learnRedux
> esw webpack.config.* src tools

/Users/folivi/Documents/projects/nodejs/learnRedux/webpack.config.dev.js (6/0)
  ✖  4:1  Rule 'no-reserved-keys' was removed and replaced by: quote-props             no-reserved-keys
  ✖  4:1  Rule 'no-wrap-func' was removed and replaced by: no-extra-parens             no-wrap-func
  ✖  4:1  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  ✖  4:1  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
  ✖  4:1  Rule 'spaced-line-comment' was removed and replaced by: spaced-comment       spaced-line-comment
  ✖  4:1  Definition for rule 'react/jsx-quotes' was not found                         react/jsx-quotes

/Users/folivi/Documents/projects/nodejs/learnRedux/src/index.js (6/1)
  ✖  4:1  Rule 'no-reserved-keys' was removed and replaced by: quote-props             no-reserved-keys
  ✖  4:1  Rule 'no-wrap-func' was removed and replaced by: no-extra-parens             no-wrap-func
  ✖  4:1  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  ✖  4:1  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
  ✖  4:1  Rule 'spaced-line-comment' was removed and replaced by: spaced-comment       spaced-line-comment
  ✖  4:1  Definition for rule 'react/jsx-quotes' was not found                         react/jsx-quotes
  !  4:1  Unexpected console statement                                                 no-console

/Users/folivi/Documents/projects/nodejs/learnRedux/tools/srcServer.js (6/0)
  ✖  1:1  Rule 'no-reserved-keys' was removed and replaced by: quote-props             no-reserved-keys
  ✖  1:1  Rule 'no-wrap-func' was removed and replaced by: no-extra-parens             no-wrap-func
  ✖  1:1  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  ✖  1:1  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
  ✖  1:1  Rule 'spaced-line-comment' was removed and replaced by: spaced-comment       spaced-line-comment
  ✖  1:1  Definition for rule 'react/jsx-quotes' was not found                         react/jsx-quotes

/Users/folivi/Documents/projects/nodejs/learnRedux/tools/startMessage.js (6/1)
  ✖  1:1  Rule 'no-reserved-keys' was removed and replaced by: quote-props             no-reserved-keys
  ✖  1:1  Rule 'no-wrap-func' was removed and replaced by: no-extra-parens             no-wrap-func
  ✖  1:1  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  ✖  1:1  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
  ✖  1:1  Rule 'spaced-line-comment' was removed and replaced by: spaced-comment       spaced-line-comment
  ✖  1:1  Definition for rule 'react/jsx-quotes' was not found                         react/jsx-quotes
  !  3:1  Unexpected console statement                                                 no-console

✖ 24 errors ! 2 warnings (2:04:38 AM)


npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! learning-redux@1.0.0 lint: `esw webpack.config.* src tools`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the learning-redux@1.0.0 lint script 'esw webpack.config.* src tools'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the learning-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     esw webpack.config.* src tools
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs learning-redux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls learning-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/folivi/Documents/projects/nodejs/learnRedux/npm-debug.log

**Comment by coryhouse** [comment]
@folivi What OS are you running? Are you having this issue with this plain starter kit?

**Comment by coryhouse** [comment]
Closing since no response.
