### ISSUE TITLE
project setup issue after integrating test

### ISSUE THREAD

**Issue by EmraanSiddiqui** [coryhouse/pluralsight-redux-starter#52]
I have posted the same question on pluralsight also:
I have recently started working on this course, but i got stuck with this error can you suggest what is the problem
![redux](https://cloud.githubusercontent.com/assets/3264483/23911858/152432ee-0904-11e7-8533-af5f2d0b7709.png)

old repository link: https://github.com/EmraanSiddiqui/react-redux-mydemo

your answer:
@SiddiquiEmraan You're missing the .babelrc and .eslintrc. Easy to overlook. You can get those from the course exercise files.

new repository link with all necessary files:
https://github.com/EmraanSiddiqui/my-react-redux-demo

Node version:
v 0.12.2
npm version:
v 4.3.0
Operating system:
Windows 10 Home
Command line used:
windows command prompt
Steps to reproduce:

just clone this repository, run npm install then try npm test

**Comment by coryhouse** [comment]
You have a typo in package.json:     "babel-prauthoreset-react-hmre": "1.1.1",
