### ISSUE TITLE
colors library is not working

### ISSUE THREAD

**Issue by walifaizy** [coryhouse/pluralsight-redux-starter#53]
Node version: 6.10.0

npm version: 3.9.5

Operating system: windows 10

Command line used: Gitbash

Steps to reproduce:
![screenshot 86](https://cloud.githubusercontent.com/assets/17082693/25067457/4c27b88c-2255-11e7-8fc7-6eb3142fe99f.png)
 
I want to display colored start message to my git bash command line screen, i am also doing the same steps described by you, install all the dependencies, but color is not changing of the startmessage, start message code is below

`import colors from "colors";
/* eslint-disable no-console */
console.log("Starting App in Dev mode.....".green);
`

**Comment by coryhouse** [comment]
Does it work for you on Windows native DOS command line?

**Comment by walifaizy** [comment]
No , it is also not working for windows native cmd line

**Comment by coryhouse** [comment]
Ah, then it's a bug in the colors library. I'd suggest switching to chalk. I've moved to it and prefer it. Better API and more reliable.

**Comment by coryhouse** [comment]
Can you share a link to your repo and open an issue on the colors project? https://github.com/Marak/colors.js/issues?q=is%3Aissue+bash+is%3Aopen

**Comment by walifaizy** [comment]
Ya,  sure Cory I will definitely  open an issue,
https://github.com/walifaizy/react-redux-library
