### ISSUE TITLE
Loading an image from my files.

### ISSUE THREAD

**Issue by raphaelbp12** [coryhouse/pluralsight-redux-starter#56]
I'm trying to load an image in a  `<img />` tag. But the address `http://localhost:3000/img/logo.png` serves me my app broken, and give me an error:

> Warning: [react-router] Location "/img/logo.png" did not match any routes

How can I do this? Thank you!

![image](https://cloud.githubusercontent.com/assets/1952333/26279353/a9f942da-3d87-11e7-847a-3efbf4318cf4.png)

**Comment by coryhouse** [comment]
You can either:
1. Require the image so it's loaded via webpack
2. Create a build step that copies the image to your build directory.
