### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by chintumundra2005** [coryhouse/pluralsight-redux-starter#6]
Hi
it seem like code getting over-ridden, i dont see files at all as you explain in plural site videos for redux and react.
can you please recommit this course code?

**Comment by coryhouse** [comment]
Please post this on the course discussion on Pluralsight.

**Comment by chintumundra2005** [comment]
ok, but how can we get the code you explained in the video ?

**Comment by coryhouse** [comment]
The final solution is available under the exercise files tab - assuming
your sub includes the option.

**Comment by chintumundra2005** [comment]
i dont see that option , will try to explore more on plural sight since i am new to that . Thanks for you time.
