### ISSUE TITLE
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by bobuva** [coryhouse/pluralsight-redux-starter#60]
Node version: 8.0.0

npm version: 5.0.1

Operating system: macOS Sierra 10.12.5

Command line used: iTerm (and platformio-ide-terminal Atom plugin)

Steps to reproduce: 
1. From the 'Environment Setup' section of the course, in 'Create start script', followed all instructions to run app in browser. In particular, run:
   npm start -s
   from Atom console.

 Title appears in browser, 'hi' message appears in Console (Chrome browser developer tools).

Even tried it without the -s on the npm start, still happens and no difference.

**Comment by coryhouse** [comment]
Sorry to hear. Does the final course exercise run for you?

**Comment by bobuva** [comment]
The final course exercise runs ok, but it still shows that error in the console.

**Comment by coryhouse** [comment]
This appears to be specific to your machine since 100's have used the final exercise without issue. Perhaps your anti-virus? https://stackoverflow.com/questions/29894154/chrome-neterr-incomplete-chunked-encoding-error

**Comment by coryhouse** [comment]
Closing. Please reply if your issue persists.
