### ISSUE TITLE
Haw to use https on production.

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [coryhouse/pluralsight-redux-starter#61]
@coryhouse can you please tell me how to redirect to https for every other url request on production. For development it is working. But i don't know how to do same for production. For development my srcServer.js code is as follows: 
 import express from 'express';
import webpack from 'webpack';
import path from 'path';
import config from '../webpack.config.dev';
import open from 'open';
import fs from 'fs';
import https from 'https';

/* eslint-disable no-console */

const port = 443;
const app = express();
const compiler = webpack(config);

app.use(require('webpack-dev-middleware')(compiler, {
  noInfo: true,
  publicPath: config.output.publicPath
}));

app.use(require('webpack-hot-middleware')(compiler));
app.use(function(req, res, next) {
    var schema = (req.headers['x-forwarded-proto'] || '').toLowerCase();
    if (schema === 'https') {
        next();
    } else {
        res.redirect('https://' + req.headers.host + req.url);
    }
});

app.get('*', function(req, res) {
  res.sendFile(path.join( __dirname, '../src/index.html'));
});

https.createServer({
    key: fs.readFileSync(path.resolve()+'/tools/key.pem'),
    cert: fs.readFileSync(path.resolve()+'/tools/cert.pem')
    }, app).listen(port, function(err){
       if (err) {
          console.log(err);
        } else {
          open(`http://localhost:${port}`);
        }
    });

**Comment by coryhouse** [comment]
Please post on the course discussion on Pluralsight instead so others can benefit. Thanks!
