### ISSUE TITLE
app not running 

### ISSUE THREAD

**Issue by constantinosergiou** [coryhouse/pluralsight-redux-starter#62]
npm version: 6.11.0

Operating system: windows 10

Command line used: npm start

Steps to reproduce:

i get this when i run npm start 
```throw new Error("cannot resolve path (or pattern) '" + path + "'"); ^ Error: cannot resolve path (or pattern)```

**Comment by constantinosergiou** [comment]
also i get this    1:1  Parsing error: The keyword 'import' is reserved

**Comment by coryhouse** [comment]
Have you went through this list? https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first

**Comment by coryhouse** [comment]
Closing since no reply, but feel free to reply if issue persists.

**Comment by constantinosergiou** [comment]
i git clone the repo and it works :) with all code inside thank you
