### ISSUE TITLE
(FYI) Chapter 12-6 Hide Preloader Based on Status: does not work when loading propType isRequired

### ISSUE THREAD

**Issue by camilomontoyau** [coryhouse/pluralsight-redux-starter#63]
Node version:8

npm version:5

Operating system:ubuntu 17.04

Command line used: npm start -S

Steps to reproduce:

**Comment by coryhouse** [comment]
The final course demo works fine for me with the loading propType required. Can you clarify the issue you're seeing?

**Comment by coryhouse** [comment]
Also, please be sure to download the final version from the course exercise files and to confirm you're seeing the issue in the final solution.

**Comment by coryhouse** [comment]
Closing since no reply received.
