### ISSUE TITLE
react-router v4 & no `IndexRoute` any more 

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [coryhouse/pluralsight-redux-starter#67]
https://github.com/gildata/pluralsight-redux-starter/issues/2

# react-router & no `IndexRoute` any more

https://github.com/ReactTraining/react-router/issues/4732

`<Route exact path="/" component={Home}/>`

===

`<IndexRoute component={Home}/>`

https://stackoverflow.com/questions/42748727/using-react-indexroute-in-react-router-v4

https://github.com/ReactTraining/react-router/issues/4732#issuecomment-317239220

**Comment by xgqfrms-GitHub** [comment]
# Where can I get the for codes of this course?

https://app.pluralsight.com/player?course=react-redux-react-router-es6

**Comment by coryhouse** [comment]
Thanks - I've provided a PR that shows how to upgrade to RR4 [here](https://github.com/coryhouse/pluralsight-redux-app-used-to-build-script/pull/1).

**Comment by xgqfrms-GitHub** [comment]
# Full codes can be found here!

https://github.com/gildata/redux-seeds
