### ISSUE TITLE
Webpack HMR not working  :3000/__webpack_hmr

### ISSUE THREAD

**Issue by piffarettig** [coryhouse/pluralsight-redux-starter#69]
Node version: v8.0.0
npm version: 5.0.0
Operating system: macOS Sierra 10.12.5
Command line used: Terminal
Steps to reproduce:

I just simply downloaded this git repo, did ```npm install``` and then ```npm start```. When the website opened, the page loaded successfully, but hot module replacement is not working. If I open developer console on chrome I get:

```[HMR] connected```
```Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING :3000/__webpack_hmr```

On Chrome:

<img width="1440" alt="screen shot 2017-07-27 at 12 28 14" src="https://user-images.githubusercontent.com/16963208/28678582-1ec172b2-72c7-11e7-9e49-f4bae4470a01.png">

On Safari:

<img width="1266" alt="screen shot 2017-07-27 at 12 29 20" src="https://user-images.githubusercontent.com/16963208/28678627-3def7df0-72c7-11e7-9375-10b8c1b3a905.png">

Same happens if I follow the Environment Setup steps by hand explained on the Pluralsight course. I tried to update webpack, webpack-dev-middleware, and webpack-hot-middleware to their latest versions, but same happens:

```
    "webpack": "^3.4.1",
    "webpack-dev-middleware": "^1.11.0",
    "webpack-hot-middleware": "^2.18.2"
```

Any thoughts on this? I googled with no luck, it seems to be something related to the node express server, that may be interfering with Hot module replacement, but really don't know what's particularly happening.  Any thoughts @coryhouse ?

Thanks in advance!

**Comment by piffarettig** [comment]
@coryhouse still stuck with this.

**Comment by coryhouse** [comment]
Hi @piffarettig - Sorry, I'm running the same stack and I can't reproduce your issue. Makes me wonder if it's related to rights on your machine.

Does the final course exercise work for you?

**Comment by piffarettig** [comment]
It's kind of weird as it both happens on Chrome, Safari and Firefox. I haven't tried the final course excersise, I'm just trying this boilerplate. Also followed the steps in your course to create the environment manually and same happens.

It's the same issue this guy has posted [here](https://github.com/glenjamin/webpack-hot-middleware/issues/21) But he mentions something related to nodemon and we are not using it.

Thanks for your answer!

**Comment by piffarettig** [comment]
Started checking other starter kits/boilerplates and saw the same happened. Made it work by updating node from v8.0.0 to v8.2.1. Reference [here](https://github.com/react-boilerplate/react-boilerplate/issues/1840#issuecomment-312996199)

Just did (on Mac):

1) Clear NPM's cache:
`sudo npm cache clean -f`
2) Install a little helper called 'n'
`sudo npm install -g n`
3) Install latest stable Node.js version
`sudo n stable`
4) Check node version:
node --version

Thanks!

**Comment by coryhouse** [comment]
Ah, great to hear that fixed it! Thanks for sharing the solution!
