### ISSUE TITLE
Not able to connect redux to react 

### ISSUE THREAD

**Issue by nerdyreact** [coryhouse/pluralsight-redux-starter#7]
Node version: v6.2.2

npm version:{ npm: '3.9.5',
  ares: '1.10.1-DEV
  http_parser: '2.7
  icu: '57.1',
  modules: '48',
  node: '6.2.2',
  openssl: '1.0.2h'
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8' }

Operating system: Windows 

Command line used:
npm install 
npm start -s 

Steps to reproduce:
Stuck at below location. 
https://app.pluralsight.com/player?course=react-redux-react-router-es6&author=cory-house&name=react-redux-react-router-es6-m7&clip=0&mode=live

For some reason I am getting an error Uncaught TypeError: Cannot read property 'courses' of undefined

home page itself gives this error

**Comment by coryhouse** [comment]
That error means courses aren't getting set to props. Your error is likely in mapStateToProps, or the course reducer.

**Comment by nerdyreact** [comment]
Here is courseReducer 

export default function courseReducer(state=[], action){

  console.log('The action type', action.type);

  switch (action.type){
    case 'CREATE_COURSE':
        return [...state,
            Object.assign({},action.course)
          ];
    default:
          return state;
  }
}

**Comment by nerdyreact** [comment]
rootReducer 

import {combineReducers} from 'redux';
import taskReducer  from './courseReducer';

const rootReducer = combineReducers({
  courses: courseReducer
});

export default rootReducer;

**Comment by nerdyreact** [comment]
CoursesPage. js 

import React, {PropTypes} from 'react';
import {connect} from 'react-redux';
import * as courseActions from '../../actions/courseActions';

class CoursesPage extends React.Component{
  constructor(props,context){
    super(props,context);

    this.state = {
      task:{name:""}
    };

    this.onNameChange = this.onNameChange.bind(this);
    this.onClickSave = this.onClickSave.bind(this);
  }

  onNameChange(event){
    const course = this.state.course;
    course.name = event.target.value;
    this.setState({course:course})
  }


  onClickSave(event){
    this.props.dispatch(courseActions.createCourse(this.state.course));
  }

  courseRow(course,index){
    return <div key={index}>{course.name}</div>;
  }

  render(){
    return (
      <div>
        <h2>Courses Page</h2>
        {this.props.courses.map(this.courseRow)}
        <h3>Add Course</h3>

        <input type="text"
               onChange={this.onNameChange}
               value={this.state.course.name}/>
        <input type="submit"
               value="Save"
               onClick={this.onClickSave} />
      </div>
    );
  }
}

CoursesPage.propTypes = {
  dispatch: React.PropTypes.func.isRequired,
  tasks: React.PropTypes.array.isRequired
}

function mapStateToProps(state){
  return{
    tasks: state.tasks
  };
}

export default connect(mapStateToProps())(CoursePage);

**Comment by nerdyreact** [comment]
You are right for some reason mapStateToProps not able to identify courses.

**Comment by coryhouse** [comment]
Your mapStateToProps says tasks: state.tasks.

It should say something like courses: state.courses.

**Comment by nerdyreact** [comment]
It says 
courses: state.courses

Error is 
Uncaught TypeError: Cannot read property 'courses' of undefined

**Comment by nerdyreact** [comment]
If you want, I can checkin the code tonight that way you can take a look at it.

**Comment by Freddy29** [comment]
I have same issue ! any solution ?
here is my courses component.
import React, {PrompTypes ,Component} from 'react';

class CoursesPage extends React.Component
{
    constructor(props, context)
    {
        super(props, context);
        this.state = {
            course : {title: ""}
        };
    }

    onTitleChange (event) {
        const course = this.state.course ;
        course.title = event.target.value;
        this.setState({course : course});
    }
    OnClickSave()
    {
    alert (`Saving ${this.state.course.title}`);

    }
    render ()
    {
        return (
            <div>
                <h1>Courses</h1>
                <h2> Add Course </h2>
                <input
                    type="text"
                    onChange={this.onTitleChange}
                    value={this.state.course.title}
                />
                <input
                    type="submit"
                    value= "Save"
                    onClick={this.OnClickSave}
                />
            </div>
        );
    }
}
export default CoursesPage;

**Comment by coryhouse** [comment]
@Freddy29 - You have a typo: `PrompTypes`. If that doesn't fix it, share your full solution on a separate GitHub repo with a description of the issue I'll give it a look.
