### ISSUE TITLE
Configuration file for JSCS not found

### ISSUE THREAD

**Issue by merlin8thomas** [coryhouse/pluralsight-redux-starter#70]
While trying to make this application on import statement I am getting an error "JSHint: 'import' is only available in ES6 (use 'esversion: 6'). (W119)" and Configuration file for JSCS not found.
Node version: 6.9.4

npm version: 3.10.10

Operating system: Windows 7 Professional 

Command line used: Webstorm internal Command Prompt and Windows Command Prompt

Steps to reproduce: Tried installing jscs dependency using package.json

**Comment by coryhouse** [comment]
Does this issue occur for you with the final course exercise available for download on the course page?

**Comment by coryhouse** [comment]
Closing since no response. Please reply if issue persists.
