### ISSUE TITLE
npm start: provided an invalid property of "name"

### ISSUE THREAD

**Issue by michelemendel** [coryhouse/pluralsight-redux-starter#74]
After working with a copy of this project, I suddenly got an error trying to run the application. The error is described here https://github.com/babel/minify/issues/205.

Solution:
Upgraded babel-cli and babel-core

**Comment by coryhouse** [comment]
Thanks for reporting! Did this issue happen when running the exact versions I specified in the course? If so, can you share your OS, Node, and npm versions?

Does this issue happen for you with the final course exercise that's provided under "Exercise files" on the course page?

**Comment by stanimirtt** [comment]
Updating to 
    "babel-cli": "6.14.0",
    "babel-core": "6.14.0",
Resolve it.

**Comment by zmetcalf** [comment]
Thanks for posting the fix @stanimirtt and @michelemendel for linking it to the other post. It helped me on another project. Have a great day all!

**Comment by michelemendel** [comment]
Hi,

Yes, I tried the demo (final course exercise) in the exercise file and also
the code in https://github.com/wags/react-redux-es6 (which I guess are the
same, but I haven't checked). The strange thing is that it worked yesterday
and this morning, and then suddenly stopped working. I haven't changed
anything.

This is on MacOS 10.12.6, Node 8.2.1, npm 5.3.0

**Comment by coryhouse** [comment]
I've tried the final exercise published on the course with Mac OS, Node 8.3 npm 5.3 and everything works fine for me. 

Does this issue happen for you with the final course exercise that's provided under "Exercise files" on the course page?

**Comment by michelemendel** [comment]
Yes

**Comment by michelemendel** [comment]
Hi,

I am working as a consultant for a government organisation, and I have used
your starter-kit for a react-redux-typescript starter-kit for some
projects. I made many changes to make it fit our needs. The applications
will mostly be used in-house and not for any commercial purposes.

For a small learning project at Ciber, we may also use the adapted
starter-kit.

The adapted starter-kit is at Github,
https://github.com/michelemendel/react-redux-starter-kit.

If the above usage, as described above, would be any problems for you,
please tell me.


Regards,

Michele Mendel
System Developer, JavaScript & frontend

+47 414 59 590
mailto:michele.mendel@ciber.no
http://www.ciber.no/

**Comment by coryhouse** [comment]
Hi Michele - No problem! Glad it's been helpful!

**Comment by coryhouse** [comment]
Closing since the new version of the course uses newer versions which should no longer have this issue.
