### ISSUE TITLE
Warning: [react-router] Location "/" did not match any routes

### ISSUE THREAD

**Issue by levantam** [coryhouse/pluralsight-redux-starter#76]
[src.zip](https://github.com/coryhouse/pluralsight-redux-starter/files/1242672/src.zip)
**Error Message in the Console log: Warning: [react-router] Location "/" did not match any routes**
![image](https://user-images.githubusercontent.com/4737016/29576400-dc25d602-8791-11e7-985a-5d0ffc8f3ab0.png)

I have a problem with my project and try to check syntax, but I can not fix it
Please help me, thanks
Course section: Initial App Structure > Create Styles, and I have attached src folder

npm: 5.3.0
All dependencies are the same with package.json

**Comment by coryhouse** [comment]
Hi, can you please upload your full source to a separate GitHub repo? The zip doesn't have all the files.

**Comment by levantam** [comment]
[pluralsight-redux-starter.zip](https://github.com/coryhouse/pluralsight-redux-starter/files/1243929/pluralsight-redux-starter.zip)
I attached my project in attachment. Thank for your response :)

**Comment by coryhouse** [comment]
Change "routers" to "routes" throughout index.js.

**Comment by levantam** [comment]
Oh, This is a stupid mistake. Thank you a lot

**Comment by Less97** [comment]
I have the same problem but I checked a couple of times all the code you wrote in the course. Any hint you could give me?
[react-pluralsight.zip](https://github.com/coryhouse/pluralsight-redux-starter/files/2548245/react-pluralsight.zip)

**Comment by coryhouse** [comment]
@Less97 - Please post a link to a GitHub repo on the course discussion board and I'll field it there. Thanks!

**Comment by Less97** [comment]
created it here https://github.com/Less97/React-Redux-PluralsightCourse thanks @coryhouse

**Comment by Less97** [comment]
I made it work through semplification and rebuilding, thanks anyway 👍
