### ISSUE TITLE
Error on npm start - Unexpected token Import

### ISSUE THREAD

**Issue by indurnath** [coryhouse/pluralsight-redux-starter#78]
I have just started with the project and while trying to run the project, I am getting an error like "Syntax Error- unexpected token import" on srcServer.js.  
I tried adding eslint-babel,  and various workarounds, but it didn't help :(
What could be the issue?

**Comment by coryhouse** [comment]
You likely don't have .babelrc defined in the root of your project. Check this list too: https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first

**Comment by indurnath** [comment]
Thank you for your quick response.  
I have .babelrc in my root folder. Still getting this error.  Attaching the npm-debug . 

[npm-debug.zip](https://github.com/coryhouse/pluralsight-redux-starter/files/1266764/npm-debug.zip)

**Comment by coryhouse** [comment]
Please provide the following:

Node version:

npm version:

Operating system:

Command line used:

**Comment by indurnath** [comment]
Node : 6.11.1
npm: 3.10.10
OS: Windows10
Editor: VS Code
Command line : windows cmd
command:  npm start (babel-node tools/srcServer.js) 

One more point,  by adding    "parser": "babel-eslint",   in .eslintrc, the warning in editor like " import is a reserved keyword" will be gone.  But still I am getting the error while running. 

Thanks.

**Comment by coryhouse** [comment]
Does the issue occur with the final course exercise on the course website?

**Comment by indurnath** [comment]
Okay, so when I clone the entire project and ran, it worked! (Y) 
 I was following the pluralsight course and was doing step by step, and then  it failed while npm start. 
 I need to figure out the real issue then. Thanks a lot for your help.

**Comment by indurnath** [comment]
I think the issue is with the  with the eslint and eslint plugin import  version conflicts. When I copied the package.json,  eslint version was 3.x and failed to install eslint import sue to peer dependency. In the starter kit which I cloned now, eslint version is 2.x.

**Comment by coryhouse** [comment]
Ah! I think I see figured out the problem. I assume you used the [package.json that I provided in this Gist](https://gist.github.com/coryhouse/7ca9541d4d2d37b2c1fef4d9b62a2ac7) to follow along with the course? I just realized it was out of sync with the final course exercise. I've updated the gist to avoid this occurring for others. Thanks so much!

**Comment by coryhouse** [comment]
I'm closing since I assume your issue is resolved now. :) 

Please reopen if the issue persists.

**Comment by amlucaszz** [comment]
I faced the same issue reported above but the suggested solution didn't work for me.
Anyhow, I find a solution. Basically, there are two steps that need to be reviewed:

1. I installed the following versions of babel packages instead:

    "babel-cli": "^6.11.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-stage-2": "^6.11.0",
    "babel-register": "^6.11.6",

2. I had to change the start statement within package.json:
    "start": "babel-node tools/srcServer.js --presets es2015,stage-2"

I hope it helps.

**Comment by coryhouse** [comment]
Thanks for sharing @amlucaszz - Instead of changing the start script, you could update .babelrc to reference the presets you've listed.
