### ISSUE TITLE
Exit status 1: Failed at the pluralsight-redux-starter@1.0.0 prestart script 'babel-node tools/startMessage.js'.

### ISSUE THREAD

**Issue by kanon4us** [coryhouse/pluralsight-redux-starter#8]
Node version:6.2.2

npm version:3.10.2

Operating system:10.11.5

Command line used:iTerm2

Steps to reproduce:npm install , npm start -s

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.2
3 info using node@v6.2.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pluralsight-redux-starter@1.0.0~prestart: pluralsight-redux-starter@1.0.0
6 verbose lifecycle pluralsight-redux-starter@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle pluralsight-redux-starter@1.0.0~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/michaelterry/Desktop/CurrentProjects/SoftwareDevelopement/CraftBeerApp/adminPannel/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle pluralsight-redux-starter@1.0.0~prestart: CWD: /Users/michaelterry/Desktop/CurrentProjects/SoftwareDevelopement/CraftBeerApp/adminPannel
9 silly lifecycle pluralsight-redux-starter@1.0.0~prestart: Args: [ '-c', 'babel-node tools/startMessage.js' ]
10 silly lifecycle pluralsight-redux-starter@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle pluralsight-redux-starter@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: pluralsight-redux-starter@1.0.0 prestart: `babel-node tools/startMessage.js`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:852:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
13 verbose pkgid pluralsight-redux-starter@1.0.0
14 verbose cwd /Users/michaelterry/Desktop/CurrentProjects/SoftwareDevelopement/CraftBeerApp/adminPannel
15 error Darwin 15.5.0
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 error node v6.2.2
18 error npm  v3.10.2
19 error code ELIFECYCLE
20 error pluralsight-redux-starter@1.0.0 prestart: `babel-node tools/startMessage.js`
20 error Exit status 1
21 error Failed at the pluralsight-redux-starter@1.0.0 prestart script 'babel-node tools/startMessage.js'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the pluralsight-redux-starter package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     babel-node tools/startMessage.js
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs pluralsight-redux-starter
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls pluralsight-redux-starter
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
`

**Comment by coryhouse** [comment]
Judging by the paths, it looks like you're creating a different app than the course outlines. If you're having an issue building the course demo app, please share your repo.

**Comment by coryhouse** [comment]
Closing since this appears to be a custom app, not an issue specific to this repo.
