### ISSUE TITLE
Maybe this is a little bug, but i could not fix out...

### ISSUE THREAD

**Issue by Coca-code** [coryhouse/pluralsight-redux-starter#80]
![err-1](https://user-images.githubusercontent.com/12387549/30814753-a6497cb0-a243-11e7-8874-fc6ff51930b5.png)
![err-2](https://user-images.githubusercontent.com/12387549/30814763-ac3ad2b8-a243-11e7-8612-8c6f2d114670.png)

**Comment by coryhouse** [comment]
Can you share your project where this is occurring on GitHub so I can try to reproduce?

**Comment by coryhouse** [comment]
Closing since no reply. Please respond if issue persists.
