### ISSUE TITLE
Deploying to an IIS Server

### ISSUE THREAD

**Issue by jamalag** [coryhouse/pluralsight-redux-starter#81]
Hi

I did a build and the files got generated in the dist folder as well as the application launching in the browser and working fine. However, when I copy the files to a folder in my IIS Server, the files load in the browser but nothing appears on the page. What could i be doing wrong?

Node version:
v8.4.0
npm version:
5.4.2
Operating system:
macOS Sierra
Command line used:
Editor command line
Steps to reproduce:
Copy the generated build files to a folder in IIS

**Comment by coryhouse** [comment]
Sorry for the slow reply. Did you get it to work? Make sure you're serving from the web root.

**Comment by jamalag** [comment]
Hi Cory, you actually gave me the same answer at Pluralsight disqus. What I still dont understand is why can it not be served from say a virtual directory. Why must it be served from the root. (However, it does work from the root)

**Comment by coryhouse** [comment]
That's just the way webpack, routing, and index.html are configured. I'm sure it's possible to host in a subdir, but I haven't tried it myself so don't have the steps to share.

**Comment by jamalag** [comment]
Thanks Cory
