### ISSUE TITLE
pasting in the HomePage.js

### ISSUE THREAD

**Issue by shloimimink** [coryhouse/pluralsight-redux-starter#82]
# Wait, try this first...
Before opening an issue, [please try these things first](https://github.com/coryhouse/pluralsight-redux-starter#having-issues-try-these-things-first).

If that list doesn't help you fix the problem, fill out the info below.

Node version:

npm version:

Operating system:

Command line used:

Steps to reproduce:

Hi, my name is Shloimi Minkowicz. 
I'm following you're course so far so good, although I'm up to in the initial app structure,
where you paste the imports react and react router and so on...in the HomePage.js,  but where are you pasting it from ? or you have to write it out manually ?

**Comment by coryhouse** [comment]
You can download the final version of the app under "exercise files" on the course home page in the final module folder. :)

**Comment by shloimimink** [comment]
We’re can I find the final version of the app ? On you’re GitHub page ?

**Comment by shloimimink** [comment]
Sorry we’re can I find the final module folder

**Comment by coryhouse** [comment]
Click on "Download exercise files" here: https://app.pluralsight.com/library/courses/react-redux-react-router-es6/exercise-files

Then open the final module folder.

**Comment by shloimimink** [comment]
Yes I figured it out before, thank you so much!!

**Comment by shloimimink** [comment]
I downloaded the exercise files, but I don’t see the final module folder in where you paste all the code from

**Comment by shloimimink** [comment]
It only shows you’re slides, there no final folder with you’re code

**Comment by coryhouse** [comment]
It's in the final module folder, but if you don't see it, this is the same thing: https://github.com/coryhouse/pluralsight-redux-app-used-to-build-script

**Comment by shloimimink** [comment]
Yes I see, but there is allot of code that you pasted in thats not on there, that I had to write manually. 
I’m up to almost the end of  9

**Comment by shloimimink** [comment]
And what does this mean ( ! DevTools failed to parse SourceMap: http://localhost:3000/bootstrap.min.css.map <http://localhost:3000/bootstrap.min.css.map>) in the console ? Should I be worried ??

**Comment by coryhouse** [comment]
What code is missing?

**Comment by shloimimink** [comment]
Just little bits here and there nothing crazy. But what worries me is this and its still running fine in the app

**Comment by shloimimink** [comment]
And no errors in the command line either

**Comment by shloimimink** [comment]
Never mind I figured it out regular s instead of S  this.setState({course: course});

Although should I be worried about this.   (!DevTools failed to parse SourceMap: http://localhost:3000/bootstrap.min.css.map <http://localhost:3000/bootstrap.min.css.map>) in the console ??

**Comment by coryhouse** [comment]
Don't worry about the css sourcemap warning. Devtools can't parse CSS sourcemaps.

**Comment by shloimimink** [comment]
Ok

**Comment by shloimimink** [comment]
Quick question, the file code  templates that you created (in module 11) , where can I find that code ? 
Or do I have to write it out.

**Comment by coryhouse** [comment]
Sorry, you'll have to type them out.

**Comment by shloimimink** [comment]
Ok, do I type it in the file code template ? And can I copy it from you ? or do you suggest I copy it from somewhere else.

**Comment by shloimimink** [comment]
I don’t mean to drive you crazy, but this warning in the terminal is bothering me. It keeps on coming up. Do you know what this means ?

**Comment by coryhouse** [comment]
I don't get this warning in the final course version: DevTools failed to parse SourceMap: http://localhost:3000/bootstrap.min.css.map <http://localhost:3000/bootstrap.min.css.map>) in the console ??

Have you tried the final course demo?

**Comment by shloimimink** [comment]
What do you mean final course demo ??

**Comment by coryhouse** [comment]
It's under the exercise files tab on the course page. Open the final module folder in the zip file and the final demo is in there.

**Comment by shloimimink** [comment]
Hey, I finished you're course it was really awesome, although I want to add a delete function. I added the delete <td> and the href in the,
CourseListRow, and copied the saved thunk and and pasted it in and wrote delete instead in the course action. Not sure what I have to do in the mangeCourse.form though ? And If I have to add anything in the other folders.  Tried bunch of different things, but they don’t seem to work.

**Comment by gechenginca** [comment]
![screen shot 2018-01-19 at 8 42 26 pm](https://user-images.githubusercontent.com/19493708/35178597-4ff8064e-fd59-11e7-9c91-d50df907c822.png)

Hi Cory,
I'm having some issue with importing `Link` form `react-router`
The version of `react-router` is @2.4.0
I found some answer from internet said `Link` was no longer in `react-router` but `react-router-dom` for 4.x version.
