### ISSUE TITLE
In production build getting some errors

### ISSUE THREAD

**Issue by SLGAURAV** [coryhouse/pluralsight-redux-starter#83]
Node version: v6.11.4

npm version: 3.10.10

Operating system: window 8.1

Command line used: cmd

Steps to reproduce: when start build for production by npm run build then show error in console.

1. warning.js:33 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details

2.warning.js:14 You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

**Comment by coryhouse** [comment]
Do you see this issue with the final course exercise posted on the course page? I'd suggest comparing your code to that.

**Comment by SLGAURAV** [comment]
i am follow whole code same as given in the course. but getting this two errors. and bundle.js size is 489kb not decrease to around 121 kb. please suggest how to resolve this errors and  bundle.js size.

**Comment by coryhouse** [comment]
The final course demo doesn't exhibit this issue, so compare your code to that.
