### ISSUE TITLE
Logic bug in courseActions

### ISSUE THREAD

**Issue by rkhaslarov** [coryhouse/pluralsight-redux-starter#84]
Hi, i find little logical bug in your course app.

in saveCourse Action you wrote this:
 course.id ? dispatch(updateCourseSuccess(course)) :
        dispatch(createCourseSuccess(course));

I think, this is wrong because every course (inserted or updated, no matter) returned from API has ID and createCourseSuccess action never be executed.  

Thank you

**Comment by FreakDroid** [comment]
Hi,

> I think, this is wrong because every course (inserted or updated, no matter) returned from API has ID and createCourseSuccess action never be executed.

 I don't think so, because when you are creating a new curse it doesn't have an Id, this is created when you call the dispatch, for this reason you are checking whether `course.id` is empty or not.

**Comment by rkhaslarov** [comment]
Please, add simple console.log to updateCourseSuccess and createCourseSuccess actions and you will see)

`
        if (course.id) {
          const existingCourseIndex = courses.findIndex(a => a.id == course.id);
          courses.splice(existingCourseIndex, 1, course);
        } else {
          //Just simulating creation here.
          //The server would generate ids and watchHref's for new courses in a real app.
          //Cloning so copy returned is passed by value rather than by reference.
          course.id = generateId(course);
          course.watchHref = `http://www.pluralsight.com/courses/${course.id}`;
          courses.push(course);
        }
        //Here course have ID anyway =)
        resolve(course);
`

**Comment by FreakDroid** [comment]
@rkhaslarov  You are right!!! Iḿ sorry. I was thinking that itś checked after the save, but no. code below:

```
export function saveCourse(course) {
  return function (dispatch, getState) {
    dispatch(beginAjaxCall());
    console.log('course ', course);
    return courseApi.saveCourse(course).then(course => {
      console.log('course.id ', course.id);
      course.id ? dispatch(updateCourseSuccess(course)) :
        dispatch(createCourseSuccess(course));
    }).catch(error => {
      dispatch(ajaxCallError(error));
      throw(error);
    });
  };
}
```

It should be:

```
export function saveCourse(course) {
  return function (dispatch, getState) {
    dispatch(beginAjaxCall());
    console.log('course ', course);
    return courseApi.saveCourse(course).then(course => {
      console.log('course.id ', course.id);
      dispatch(updateCourseSuccess(course))
    }).catch(error => {
      dispatch(ajaxCallError(error));
      throw(error);
    });
  };
}
```

Keeping only the update.

**Comment by FreakDroid** [comment]
The example is correct, the only problem that we have is a scope problem, because we are using the `course.id` that it is inside the promise, and we must use the course.id outside the promise, and if you notice we are using the same so the scope is replaced so:

```
export function saveCourse(course) {
  return function (dispatch, getState) {
    dispatch(beginAjaxCall());
    return courseApi.saveCourse(course).then(courseSaved => {
      console.log('course.id ', course.id);
      course.id ? dispatch(updateCourseSuccess(courseSaved )) :
        dispatch(createCourseSuccess(courseSaved ));
    }).catch(error => {
      dispatch(ajaxCallError(error));
      throw(error);
    });
  };
}
```

Now it is calling the correct dispatch.

**Comment by coryhouse** [comment]
Thanks @FreakDroid - Yep, that's correct. Good catch on my mistake @rkhaslarov!

**Comment by coryhouse** [comment]
This repository is only for the starter kit, so the code being discussed here isn't actually in this repo. So instead, I've resolved this issue [in the update branch on a separate repository that contains the final course demo](https://github.com/coryhouse/pluralsight-redux-app-used-to-build-script/pull/1). [Here's the issue on that repo](https://github.com/coryhouse/pluralsight-redux-app-used-to-build-script/issues/4)

So closing this issue since handled separately in the other repo.
