### ISSUE TITLE
when reload the browser in route course/:id

### ISSUE THREAD

**Issue by mhesham32** [coryhouse/pluralsight-redux-starter#88]
i get this error instead of getting an empty form 

> Uncaught SyntaxError: Unexpected token <

**Comment by coryhouse** [comment]
Does the initial page load okay?

**Comment by mhesham32** [comment]
every thing is ok wjen I click a course link i got the data of the course in the form but when reload i got the error and it says the error is in th bundle.js string-1 in the html page 
```
<html lang="en">
```

**Comment by coryhouse** [comment]
That's odd. I suggest comparing your project to the final course exercise available under exercise files on the course page (look in the final module folder of the zip file).

If that doesn't help, please share a link to your project on a GitHub repo and I'll give it a look.

**Comment by mhesham32** [comment]
https://github.com/mhesham32/React-Redux

**Comment by coryhouse** [comment]
Wow, this one took me awhile to hunt down, but it's an easy mistake to make: In index.html, reference bundle.js with a leading slash. :)

https://github.com/mhesham32/React-Redux/blob/master/src/index.html#L10
