### ISSUE TITLE
Production build not using/loading correct css styling

### ISSUE THREAD

**Issue by pparkergithub** [coryhouse/pluralsight-redux-starter#89]
Node version: 8.9.3

npm version: 5.5.1

Operating system: windows

Command line used: cmd, used through Webstorm

Steps to reproduce:
**I am using all the latest packages for everything used in the course. So I have followed everything done in the course as closely as I could, but with a few changes where the updated packages do things differently. Like the latest version of Webpack, the config file uses- modules : { rules : [ {test: '', use: ''} ] }, as opposed to what you have in the course as- modules: { loaders: [ {test: '', loader: '' } ] }. **

I run the production build, and it compiles, builds, and runs with no errors. The site loads up in my browser but it does not have any of the css styling (like no jumbotron, navbar, etc.). It is still working fine with the staging build, so I do not know why I am not getting any styling. 

please let me know if you need to see any files or code

**Comment by pparkergithub** [comment]
here is a link to how I have built the project with all the latest packages: https://github.com/pparkergithub/react_redux_es6

**Comment by coryhouse** [comment]
Hi @pparkergithub - Good news: Here's a PR that shows how to update the course demo to use all the latest versions: https://github.com/coryhouse/pluralsight-redux-app-used-to-build-script/pull/1

**Comment by pparkergithub** [comment]
thank you

**Comment by pparkergithub** [comment]
sorry to bother you again @coryhouse , but after reviewing and applying the changes you linked in your response I am still having the issue with my css styling in the production build

**Comment by coryhouse** [comment]
Hrmmm, please share a repo that shows the problem and describes how to replicate it.
