### ISSUE TITLE
ESLint: App not found in './components/App' (import/named)

### ISSUE THREAD

**Issue by vijaygawade18** [coryhouse/pluralsight-redux-starter#95]
Hi @coryhouse, I am getting 'App not found in './components/App' error and i am not able to access the exported component's due to this issue.

**Comment by vijaygawade18** [comment]
@coryhouse, my index.js file is at root level and App.js file is in components folder which is also at root level. 

Here is my App.js component snippet:

class App extends React.Component {
   render() {
       return(<div>App component</div>);
    }
}

exports default App;  

Thanks!

**Comment by coryhouse** [comment]
please share your work on a GitHub repo and I'll give it a look

**Comment by coryhouse** [comment]
Actually, correction, I see your problem: Change `exports default App;` to `export default App;`
